"use client";

import { useState } from "react";
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogDescription,
    DialogFooter
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue
} from "@/components/ui/select";
import { StockItem, ArcadeMachine, RevenueEntry } from "@/types";
import { revenueService } from "@/services";
import { toast } from "sonner";
import { DollarSign, Calendar, Hash, StickyNote } from "lucide-react";
import { generateId } from "@/lib/utils";

interface LogRevenueDialogProps {
    isOpen: boolean;
    onOpenChange: (open: boolean) => void;
    item: StockItem;
    machines?: ArcadeMachine[];
    userId?: string;
    onSuccess?: () => void;
}

export function LogRevenueDialog({
    isOpen,
    onOpenChange,
    item,
    machines = [],
    userId = "system",
    onSuccess
}: LogRevenueDialogProps) {
    const [amount, setAmount] = useState("");
    const [playCount, setPlayCount] = useState("");
    const [machineId, setMachineId] = useState<string>("");
    const [date, setDate] = useState(new Date().toISOString().split("T")[0]);
    const [notes, setNotes] = useState("");
    const [isSubmitting, setIsSubmitting] = useState(false);

    const selectedMachine = machines.find(m => m.id === machineId);

    const handleSubmit = async () => {
        const parsedAmount = parseFloat(amount);
        if (isNaN(parsedAmount) || parsedAmount <= 0) {
            toast.error("Invalid Amount", { description: "Please enter a valid revenue amount." });
            return;
        }

        setIsSubmitting(true);
        try {
            const entry: Omit<RevenueEntry, "id"> = {
                itemId: item.id,
                itemName: item.name,
                machineId: machineId && machineId !== "none" ? machineId : undefined,
                machineName: selectedMachine?.name,
                amount: parsedAmount,
                playCount: playCount ? parseInt(playCount) : undefined,
                date: new Date(date),
                notes: notes || undefined,
                createdBy: userId,
                createdAt: new Date()
            };
            const entryId = generateId();
            await revenueService.set(entryId, entry);

            toast.success("Revenue Logged", {
                description: `$${parsedAmount.toFixed(2)} recorded for ${item.name}`
            });

            // Reset form
            setAmount("");
            setPlayCount("");
            setMachineId("");
            setNotes("");
            setDate(new Date().toISOString().split("T")[0]);

            onOpenChange(false);
            onSuccess?.();
        } catch (error) {
            console.error("Failed to log revenue:", error);
            toast.error("Error", { description: "Failed to log revenue entry." });
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <Dialog open={isOpen} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-md">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2">
                        <DollarSign className="h-5 w-5 text-green-600" />
                        Log Revenue
                    </DialogTitle>
                    <DialogDescription>
                        Record revenue generated by <strong>{item.name}</strong>
                    </DialogDescription>
                </DialogHeader>

                <div className="space-y-4 py-4">
                    {/* Amount */}
                    <div className="space-y-2">
                        <Label htmlFor="amount" className="flex items-center gap-1">
                            <DollarSign className="h-3.5 w-3.5" />
                            Amount *
                        </Label>
                        <div className="relative">
                            <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
                            <Input
                                id="amount"
                                type="number"
                                step="0.01"
                                min="0"
                                placeholder="0.00"
                                value={amount}
                                onChange={(e) => setAmount(e.target.value)}
                                className="pl-7"
                            />
                        </div>
                    </div>

                    {/* Play Count (Optional) */}
                    <div className="space-y-2">
                        <Label htmlFor="playCount" className="flex items-center gap-1">
                            <Hash className="h-3.5 w-3.5" />
                            Play Count (optional)
                        </Label>
                        <Input
                            id="playCount"
                            type="number"
                            min="0"
                            placeholder="Number of plays"
                            value={playCount}
                            onChange={(e) => setPlayCount(e.target.value)}
                        />
                    </div>

                    {/* Machine Selection (Optional) */}
                    {machines.length > 0 && (
                        <div className="space-y-2">
                            <Label>Machine (optional)</Label>
                            <Select value={machineId} onValueChange={setMachineId}>
                                <SelectTrigger>
                                    <SelectValue placeholder="Select machine..." />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="none">No specific machine</SelectItem>
                                    {machines.map(m => (
                                        <SelectItem key={m.id} value={m.id}>
                                            {m.name} ({m.location})
                                        </SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>
                    )}

                    {/* Date */}
                    <div className="space-y-2">
                        <Label htmlFor="date" className="flex items-center gap-1">
                            <Calendar className="h-3.5 w-3.5" />
                            Date
                        </Label>
                        <Input
                            id="date"
                            type="date"
                            value={date}
                            onChange={(e) => setDate(e.target.value)}
                        />
                    </div>

                    {/* Notes (Optional) */}
                    <div className="space-y-2">
                        <Label htmlFor="notes" className="flex items-center gap-1">
                            <StickyNote className="h-3.5 w-3.5" />
                            Notes (optional)
                        </Label>
                        <Textarea
                            id="notes"
                            placeholder="Any additional notes..."
                            value={notes}
                            onChange={(e) => setNotes(e.target.value)}
                            rows={2}
                        />
                    </div>
                </div>

                <DialogFooter>
                    <Button variant="outline" onClick={() => onOpenChange(false)}>
                        Cancel
                    </Button>
                    <Button
                        onClick={handleSubmit}
                        disabled={isSubmitting || !amount}
                        className="bg-green-600 hover:bg-green-700"
                    >
                        {isSubmitting ? "Saving..." : "Log Revenue"}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
